"""Base distribution class"""

from typing import TYPE_CHECKING, Any, Literal, Callable, cast
from pathlib import Path
from functools import cached_property

import numpy as np
import scipy
import seaborn as sns
from numba import njit, prange
from astropy import constants, cosmology
from numpy.typing import NDArray
from astropy.units import Unit, Quantity, def_unit
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from astropy.units.typing import UnitLike

from src import rng, plot, utils, report, physics, run_units, agama_wrappers
from src.types import FloatOrArray, ParticleType, QuantitySpline, QuantityInterpolate

from . import io

if TYPE_CHECKING:
    from ..phase_space import PhaseSpace

Backends = Literal['python', 'agama']

PhysicalProperty = Literal[
    'density', 'velocity dispersion', 'temperature', 'pressure', 'internal energy', 'enclosed_mass'
]


class Distribution:
    """General mass distribution profile."""

    def __init__(
        self,
        r_min: Quantity['length'] = Quantity(1e-4, 'kpc'),
        r_max: Quantity['length'] | None = None,
        r_s: Quantity['length'] | None = None,
        r_half_light: Quantity['length'] | None = None,
        c: int | float | None | Literal['From mass'] = None,
        r_vir: Quantity['length'] | None = None,
        total_mass: Quantity['mass'] | None = None,
        rho_s: Quantity['mass density'] | None = None,
        space_steps: float | int = 1e3,
        spline_s: float | None = None,
        truncate: bool = False,
        truncate_power: int = 4,
        label: str = '',
        particle_type: ParticleType = 'dm',
        name: str = '',
        id: int | None = None,
        backend: Backends = 'agama',
        agama_potential: agama_wrappers.Potential | None = None,
        agama_total_potential: agama_wrappers.Potential | None = None,
        agama_truncation_power: int = 20,
        agama_save_params: dict[str, Any] = {},
        **kwargs: Any,
    ) -> None:
        """General mass distribution profile.

        Parameters:
            r_min: Minimum radius of the density profile, used for calculating the `internal logarithmic grid` and set internal cutoffs.
            r_max: Maximum radius of the density profile, used for calculating the `internal logarithmic grid` and set internal cutoffs.
            r_s: Scale radius of the distribution profile.
            r_half_light: Half-light radius of the distribution profile.
            c: Concentration parameter of the distribution profile (such that r_vir = c * r_s). If 'From mass', calculate it based on the total mass (must be provided via `total_mass`).
            r_vir: Virial radius of the distribution profile.
            rho_s: Scale density of the distribution profile. Either `total_mass` or `rho_s` must be provided, and the other will be calculated from the rest of the parameters. If both are provided, they are hard set with no attempts to reconcile the parameters.
            total_mass: Total mass of the distribution profile. Either `total_mass` or `rho_s` must be provided, and the other will be calculated from the rest of the parameters. If both are provided, they are hard set with no attempts to reconcile the parameters.
            space_steps: Number of space steps for the `internal logarithmic grid`.
            spline_s: Spline smoothing parameter for calculating the drho/dpotential derivative.
            truncate: Whether to truncate the density at the virial radius.
            truncate_power: The power law used for truncation.
            label: Label for the density profile.
            name: Additional name for the distribution profile.
            id: Unique identifier for the distribution profile.
            bypass_init_checks: Whether to bypass initialization checks.
            backend: Backend to use for calculations. Either 'python' (explicit functions defined in this class) or 'agama' (create the relevant potential and distribution functions on the fly and forward the calculations to them).
            agama_potential: agama potential to use, describing this distribution in isolation. If `None` one will be autogenerated. Only relevant if `backend` is 'agama'.
            agama_total_potential: agama potential to use, describing the total potential of all distributions in the system. If `None` one will be autogenerated. Only relevant if `backend` is 'agama'.
            agama_truncation_power: Truncation to use for the agama potential. Replaces `truncate_power` if `backend` is 'agama'.
            agama_save_params: Parameters to save for the agama potential.
            **kwargs: Unused keyword arguments.

        Returns:
            General mass distribution object.
        """

        self.space_steps: int = int(space_steps)
        self.title = 'General'
        self.particle_type: ParticleType = particle_type
        self._label: str = label
        self.name: str = name

        self.spline_s = spline_s
        self.truncate = truncate
        self.truncate_power = truncate_power
        self.id = utils.make_id(id)
        self.backend: Backends = backend

        if c == 'From mass':
            assert total_mass is not None, 'total_mass must be provided when using Dutton14'
            self.total_mass = cast(Quantity, total_mass.to(run_units.mass))
            c = self.calculate_c()

        if r_s is None and r_half_light is not None:
            r_s = self.r_half_light_to_r_s(r_half_light)

        if r_s is not None and r_vir is not None:
            c = (r_vir / r_s).decompose(run_units.system).value
        elif r_s is not None and c is not None:
            r_vir = Quantity(c * r_s.to(run_units.length))
        elif r_vir is not None and c is not None:
            r_s = Quantity(r_vir.to(run_units.length) / c)

        if (r_s is not None and rho_s is not None) and (c is None and r_vir is None):
            self.r_s = r_s.to(run_units.length)
            self.rho_s = rho_s.to(run_units.density)
            params = self.calculate_virial_from_scales()
            r_vir = params['r_vir']
            total_mass = params['total_mass']
            c = float(params['c'])

        assert r_s is not None, 'Failed to evaluate r_s'
        self.r_s: Quantity['length'] = cast(Quantity, r_s.to(run_units.length))

        assert r_vir is not None, 'Failed to evaluate r_vir'
        self.r_vir: Quantity['length'] = cast(Quantity, r_vir.to(run_units.length))

        assert c is not None, 'Failed to evaluate c'
        self.c: float = c

        self.r_min: Quantity['length'] = cast(Quantity, r_min.to(run_units.length))
        self.r_max: Quantity['length'] = cast(
            Quantity, (r_max if r_max is not None else 85 * self.r_s).to(run_units.length)
        )

        assert total_mass is not None or rho_s is not None, 'Either total_mass or rho_s must be specified'

        if total_mass is not None:
            self.total_mass = cast(Quantity, total_mass.to(run_units.mass))
        if rho_s is not None:
            self.rho_s: Quantity['mass density'] = cast(Quantity, rho_s.to(run_units.density))

        if total_mass is None:
            self.total_mass = self.calculate_total_mass()
        if rho_s is not None:
            self.rho_s = self.calculate_density_scale()

        if self.backend == 'agama':
            self.truncate_power = agama_truncation_power
            self.agama_potential = agama_potential if agama_potential is not None else self.to_agama_potential()
            self.agama_total_potential = (
                agama_total_potential if agama_total_potential is not None else self.to_agama_potential()
            )
        else:
            self.agama_potential = None
            self.agama_total_potential = None

        self.agama_save_params = agama_save_params

    def __repr__(self):
        return str(self.report)

    def __call__(self, r: Quantity['length']) -> Quantity['mass density']:
        """Calculate `rho(r)`"""
        return self.density(r)

    def to_scale(self, x: Quantity['length']) -> Quantity['dimensionless']:
        """Scale the distance, i.e. `x/r_s`"""
        return x.to(self.r_s.unit) / self.r_s

    @property
    def report(self) -> report.Report:
        """Generate a report of the distribution's properties"""
        warn = '' if self.physical else 'WARNING: This distribution is not physical.\n\n'
        return report.Report(
            body_lines=[
                report.Line(title='name', value=self.name),
                report.Line(title='particle type', value=self.particle_type),
                report.Line(title='r_s', value=self.r_s, format='.4f'),
                report.Line(title='c', value=self.c, format='.1f'),
                report.Line(title='r_vir', value=self.r_vir, format='.4f'),
                report.Line(title='total_mass', value=self.total_mass, format='.3e'),
                report.Line(title='rho_s', value=self.rho_s, format='.3e'),
                report.Line(title='dynamical_time', value=(1 * self.dynamical_time).to(run_units.time), format='.4f'),
                report.Line(title='r_min', value=self.r_min, format='.4f'),
                report.Line(title='r_max', value=self.r_max, format='.4f'),
                report.Line(title='space steps', value=self.space_steps, format='.0e'),
            ],
            header=f'{warn}{self.title} density function (ID={self.id})',
            body_prefix='  - ',
        )

    def calculate_c(
        self,
        mass: Quantity['mass'] | None = None,
        method: Literal['Dutton14'] = 'Dutton14',
        delta: Literal[200, 'vir'] = 'vir',
    ) -> float:
        """Calculate the concentration parameter `c` from the total mass based on Dutton & Maccio (2014) arXiv:1402.7073v2.

        Parameters:
            mass: The total mass of the distribution. If `None`, use the internal `total_mass` parameter.
            method: The method to use for calculating the concentration parameter. Only 'Dutton14' is supported.
            delta: The concentration type. Only 200 (as a number) and 'vir' are supported.

        Returns:
            c
        """
        if mass is None:
            mass = cast(Quantity, self.total_mass.to('Msun'))
        assert method == 'Dutton14', f'Unsupported method: {method}. Only Dutton14 is supported'
        if method == 'Dutton14':
            assert delta in [200, 'vir'], f'Unsupported delta: {delta}. Only 200 (as a number) and "vir" are supported'
            log_m = np.log10((mass * cosmology.Planck18.h / Quantity(1e12, 'Msun')).value)
            if delta == 'vir':
                log_c = 1.025 - 0.097 * log_m
            elif delta == 200:
                log_c = 0.905 - 0.101 * log_m
            return 10**log_c

    def theoretical_enclosed_mass(self, r: Quantity['length']) -> Quantity['mass']:
        """Calculate the enclosed mass based on the theoretical density profile (without truncation)."""
        raise NotImplementedError(
            'Theoretical enclosed mass calculation must be implemented for the subclass (if you see this error it means the code is reaching the base class instead).'
        )

    def calculate_virial_from_scales(self, **kwargs: Any) -> dict[str, Quantity]:
        """Calculate the total mass and virial radius from the scale radius (`r_s`) and scale density (`rho_s`).

        Optimize for the virial radius and `Delta` such that the enclosed mass at `r_vir` is the same as when calculated from `Delta*rho_crit`, while at the same time maintaining the mass-concentration relations from Dutton14.

        Parameters:
            **kwargs: Additional keyword arguments passed to the solver (`scipy.optimize.least_squares`).

        Returns:
            A dict with the keys: `r_vir` (Quantity), `total_mass` (Quantity), `c` (float).
        """

        def m_crit(r_vir: Quantity['length'], delta: float) -> Quantity['mass']:
            return 4 / 3 * np.pi * r_vir**3 * delta * cosmology.Planck18.critical_density0.decompose(run_units.system)

        def equation(params: tuple[float, float]) -> tuple[float, float]:
            """Helper function for the optimizer"""
            r_vir, delta = params
            r_vir = Quantity(r_vir, 'kpc')
            c = self.to_scale(r_vir)
            total_mass = Quantity([self.theoretical_enclosed_mass(r_vir), m_crit(r_vir, delta)])
            return (
                float((cast(Quantity, total_mass.diff()[0])) / total_mass.mean()),
                float((self.calculate_c(mass=cast(Quantity, total_mass.mean())) - c) / c),
            )

        results = scipy.optimize.least_squares(equation, (self.r_s.value, 200), **kwargs).x
        r_vir = Quantity(results[0], run_units.length)
        delta: float = results[1]
        if kwargs.get('verbose', 0) > 0:
            print(f'Optimization reached with Delta={delta}')
        return {
            'r_vir': r_vir,
            'total_mass': Quantity([self.theoretical_enclosed_mass(r_vir), m_crit(r_vir, delta)]).mean(),
            'c': r_vir / self.r_s,
        }

    @staticmethod
    def r_half_light_to_r_s(r: Quantity['length'], projection_factor: float = 1.8) -> Quantity['length']:
        """Calculates the scale radius (`r_s`) from the half-light radius."""
        return projection_factor * r / (1 + np.sqrt(2))

    @property
    def label(self) -> str:
        """Return the label of the profile."""
        if self._label == '':
            if self.particle_type == 'dm':
                return 'DM'
            elif self.particle_type == 'baryon':
                return 'Baryonic matter'
        return self._label

    @label.setter
    def label(self, label: str) -> None:
        self._label = label

    @property
    def physical(self) -> bool:
        """Return whether the profile is physical."""
        return True

    @cached_property
    def dynamical_time(self) -> Unit:
        """Calculate the dynamic time of the profile, returning it as a `Unit` object."""
        return def_unit(
            'dynamical_time',
            np.sqrt(self.r_s**3 / (constants.G * self.total_mass)).to(run_units.time),
            doc=f'{self.title} dynamic time',
        )

    def scatter_time_scale(self, sigma: Quantity[run_units.cross_section]) -> Quantity['time']:
        """Time scale between scatter events"""
        return 1 / np.sqrt((4 * np.pi * constants.G * self.r_s**2 * self.rho_s**3 * sigma**2)).decompose(
            run_units.system
        )

    def to_agama_potential(
        self, type: str | None = None, gamma: int | None = None, beta: int | None = None, **kwargs: Any
    ) -> agama_wrappers.Potential:
        """Generate an agama potential from the distribution."""
        return agama_wrappers.Potential(
            **utils.drop_None(
                type=type,
                gamma=gamma,
                beta=beta,
                outerCutoffRadius=self.r_vir.value if self.truncate else None,
                cutoffStrength=self.truncate_power if self.truncate else None,
            ),
            mass=self.total_mass.value,
            scaleRadius=self.r_s.value,
            **kwargs,
        )

    def to_agama_df(
        self,
        type: str = 'QuasiSpherical',
        potential: agama_wrappers.Potential | None = None,
        density: agama_wrappers.Potential | None = None,
        **kwargs: Any,
    ) -> agama_wrappers.DistributionFunction:
        """Generate an agama distribution function from the distribution."""
        return agama_wrappers.DistributionFunction(
            type=type,
            potential=potential if potential is not None else self.agama_total_potential,
            density=density if density is not None else self.agama_potential,
            **kwargs,
        )

    @property
    def agama_df(self) -> agama_wrappers.DistributionFunction:
        """Generate an agama distribution function from the distribution."""
        return self.to_agama_df()

    def radius_enclosing_scaledup_mass(
        self, core_radius: Quantity = Quantity(0.2, 'kpc'), sizeup_factor: float = 3
    ) -> float:
        """Return the radius enclosing a mass of M(core_radius) * `sizeup_factor`, used to estimate the radius of collapsing halo during core collapse."""
        r_prime = self.geomspace_grid[
            np.argmin(np.abs(self.enclosed_mass_grid - self.enclosed_mass(core_radius) * sizeup_factor))
        ]
        return self.to_scale(cast(Quantity, r_prime)).value

    def tc0(
        self, C: float = 0.9, sigma: Quantity[run_units.cross_section] = Quantity(50, 'cm^2/g')
    ) -> Quantity['time']:
        """Base estimation for the core collapse time"""
        return (
            150 / C * 1 / (sigma * self.rho_s) * 1 / np.sqrt(4 * np.pi * constants.G * self.rho_s * self.r_s**2)
        ).to(run_units.time)

    def tc(self, J: float = 1, sigma: Quantity[run_units.cross_section] = Quantity(50, 'cm^2/g')) -> Quantity['time']:
        """New estimation for the core collapse time"""
        return (
            1 / (4 * np.pi * self.rho_s * sigma) * 1 / np.sqrt(4 * np.pi * constants.G * self.rho_s * self.r_s**2) * J
        ).to(run_units.time)

    @cached_property
    def geomspace_grid(self) -> Quantity['length']:
        """Calculate the `internal logarithmic grid`."""
        return cast(Quantity, np.geomspace(self.r_min, self.r_max, self.space_steps))

    @staticmethod
    @njit
    def calculate_density(
        r: FloatOrArray,
        rho_s: float = 1,
        r_s: float = 1,
        r_vir: float = 1,
        truncate: bool = False,
        truncate_power: int = 4,
    ) -> FloatOrArray:
        """Calculate the density (`rho`) at a given radius.

        This method is meant to be overwritten by subclasses. The function gets called by njit parallelized functions and must be njit compatible.

        Parameters:
            r: The radius at which to calculate the density.
            rho_s: The scale density.
            r_s: The scale radius.
            r_vir: The virial radius.
            truncate: Whether to truncate the density at the virial radius.
            truncate_power: The power law used for truncation.

        Returns:
            The density at the given radius.
        """
        return r

    def density(self, r: Quantity['length']) -> Quantity['mass density']:
        """Calculate the density (`rho`) at a given radius."""
        if self.backend == 'agama':
            assert self.agama_potential is not None, 'Agama potential not initialized'
            return self.agama_potential.density(r)
        return Quantity(
            self.calculate_density(
                r=r.to(run_units.length).value,
                rho_s=self.rho_s.decompose(run_units.system).value,
                r_s=self.r_s.decompose(run_units.system).value,
                r_vir=self.r_vir.decompose(run_units.system).value,
                truncate=self.truncate,
                truncate_power=self.truncate_power,
            ),
            run_units.density,
        )

    def calculate_velocity_dispersion(self, r: Quantity['length']) -> Quantity['velocity']:
        """Calculate the velocity dispersion at the provided radius, assuming isotropy. Only implemented for the AGAMA backend."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Velocity dispersion is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.agama_df.velocity_dispersion(r)

    @cached_property
    def velocity_dispersion_grid(self) -> Quantity['specific energy']:
        """Calculate the velocity dispersion at the `internal logarithmic grid`."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Velocity dispersion calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.calculate_velocity_dispersion(self.geomspace_grid)

    def calculate_temperature(self, r: Quantity['length']) -> Quantity['specific energy']:
        """Calculate the temeprature at the provided radius, assuming isotropy. Only implemented for the AGAMA backend."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Temperature calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return cast(Quantity, 3 * self.calculate_velocity_dispersion(r) ** 2)

    @cached_property
    def temperature_grid(self) -> Quantity['specific energy']:
        """Calculate the temperature at the `internal logarithmic grid`."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Temperature calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.calculate_temperature(self.geomspace_grid)

    def calculate_pressure(self, r: Quantity['length']) -> Quantity['pressure']:
        """Calculate the pressure at the provided radius, assuming isotropy. Only implemented for the AGAMA backend."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Pressure calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return cast(Quantity, self.density(r) * self.calculate_velocity_dispersion(r) ** 2)

    @cached_property
    def pressure_grid(self) -> Quantity['pressure']:
        """Calculate the pressure at the `internal logarithmic grid`."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Pressure calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.calculate_pressure(self.geomspace_grid)

    def calculate_internal_energy(self, r: Quantity['length']) -> Quantity['specific energy']:
        """Calculate the internal energy at the provided radius, assuming isotropy. Only implemented for the AGAMA backend."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Internal energy calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return cast(Quantity, 3 / 2 * self.calculate_velocity_dispersion(r) ** 2)

    @cached_property
    def internal_energy_grid(self) -> Quantity['specific energy']:
        """Calculate the internal energy at the `internal logarithmic grid`."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Internal energy calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.calculate_internal_energy(self.geomspace_grid)

    def calculate_entropy(self, r: Quantity['length']) -> Quantity:
        """Calculate the entropy at the provided radius, assuming isotropy. Only implemented for the AGAMA backend."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Entropy calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return Quantity(
            np.log(
                (self.calculate_velocity_dispersion(r) ** 3 / self.calculate_temperature(r))
                .decompose(run_units.system)
                .value
            ),
        )

    @cached_property
    def entropy_grid(self) -> Quantity:
        """Calculate the entropy at the `internal logarithmic grid`."""
        if self.backend != 'agama':
            raise NotImplementedError(
                f'Entropy calculation is only implemented for AGAMA backend, not for {self.backend}'
            )
        return self.calculate_entropy(self.geomspace_grid)

    @cached_property
    def density_grid(self) -> Quantity['mass density']:
        """Calculate the density (`rho`) at the `internal logarithmic grid`."""
        return self.density(self.geomspace_grid)

    def density_r2(self, r: Quantity['length']) -> Quantity['linear density']:
        """Calculate the density (`rho`) times the jacobian (`r^2`) at a given radius."""
        return self.density(r) * r.to(run_units.length) ** 2

    @cached_property
    def density_r2_grid(self) -> Quantity['linear density']:
        """Calculate the density (`rho`) times the jacobian (`r^2`) at the  `internal logarithmic grid`."""
        return self.density_r2(self.geomspace_grid)

    def spherical_density_integrate(self, r: Quantity['length'], use_rho_s: bool = True) -> Quantity['mass']:
        """Calculate the density (`rho`) integral in `[0,r]` assuming spherical symmetry. `use_rho_s` is used internally to calculate the density scale and shouldn't be used."""
        rho_s = self.rho_s.decompose(run_units.system).value if use_rho_s else 1
        integral = utils.fast_spherical_density_integrate(
            np.atleast_1d(r.to(run_units.length).value),
            self.calculate_density,
            rho_s,
            self.r_s.decompose(run_units.system).value,
            self.r_vir.decompose(run_units.system).value,
        )
        return Quantity(integral, run_units.mass)

    def enclosed_mass(self, r: Quantity['length']) -> Quantity['mass']:
        """Calculate the enclosed mass (`M(<=r)`) at a given radius. Integrates the density function (`rho`)."""
        scalar_input = np.isscalar(r)
        if len(r.shape) == 2:
            enclosed_mass = Quantity([self.spherical_density_integrate(r_) for r_ in r])
        else:
            enclosed_mass = self.spherical_density_integrate(r)
        if scalar_input:
            return Quantity(np.array(enclosed_mass)[0], run_units.mass)
        return enclosed_mass

    @cached_property
    def enclosed_mass_grid(self) -> Quantity['mass']:
        """Calculate the enclosed mass (`M(<=r)`) at the  `internal logarithmic grid`."""
        return self.enclosed_mass(self.geomspace_grid)

    @cached_property
    def enclosed_mass_spline(self) -> QuantitySpline:
        """Calculate a spline of the enclosed mass (`M(<=r)`)"""
        return QuantitySpline(
            x=self.geomspace_grid,
            y=self.enclosed_mass_grid,
            ext='const',
        )

    def calculate_total_mass(self) -> Quantity['mass']:
        """Calculate the total mass, i.e. the integral over `[0, r_max]`."""
        return cast(Quantity, self.spherical_density_integrate(self.r_max, True)[0])

    def calculate_density_scale(self) -> Quantity['mass density']:
        """Calculate the density scale to set the integral over `[0, r_max]` to equal `total_mass`."""
        return self.total_mass / self.spherical_density_integrate(self.r_max, False)[0] * run_units.density

    def mass_pdf(self, r: Quantity['length']) -> FloatOrArray:
        """Mass probability density function (pdf) at radius `r`. Normalized `rho*r^2`."""
        mass_pdf = self.density_r2(r).value
        mass_pdf /= np.trapezoid(mass_pdf, r.decompose(run_units.system).value)
        return mass_pdf

    def mass_cdf(self, r: Quantity['length']) -> FloatOrArray:
        """Mass cumulative probability density function (cdf) at radius `r`. Normalized enclosed mass."""
        return (self.enclosed_mass(r) / self.total_mass).decompose(run_units.system).value

    @cached_property
    def pdf(self) -> QuantityInterpolate:
        """Mass probability density function (pdf) interpolated at a given radius."""
        return QuantityInterpolate(
            x=self.geomspace_grid.value,
            y=self.mass_pdf(self.geomspace_grid),
            kind='cubic',
            bounds_error=False,
            fill_value=(0, 0),
        )

    @cached_property
    def cdf(self) -> QuantityInterpolate:
        """Mass cumulative probability density function (cdf) interpolated at a given radius `r`."""
        return QuantityInterpolate(
            x=self.geomspace_grid.value,
            y=self.mass_cdf(self.geomspace_grid),
            kind='cubic',
            bounds_error=False,
            fill_value=(0, 1),
        )

    @cached_property
    def quantile_function(self) -> QuantityInterpolate:
        """Mass quantile function (inversed cdf) interpolated at a given radius `r`."""
        cdf, rs = utils.joint_clean(arrays=[self.mass_cdf(self.geomspace_grid), self.geomspace_grid.value])
        return QuantityInterpolate(
            x=cdf, y=rs, kind='cubic', bounds_error=False, fill_value=(self.r_min.value, self.r_max.value)
        )

    def poisson_potential(self, r: Quantity['length']) -> Quantity['specific energy']:
        """Calculate the gravitational potential energy (`poisson_potential`), at a given radius `r`."""
        if self.backend == 'agama':
            assert self.agama_total_potential is not None, 'Agama potential not initialized'
            return self.agama_total_potential.poisson_potential(r).to(run_units.specific_energy)
        xs = Quantity(np.geomspace(self.r_min, r, 1000), 'kpc').T
        return np.trapezoid(y=constants.G * self.enclosed_mass(xs) / xs**2, x=xs).to(run_units.specific_energy)

    @cached_property
    def potential_reference(self) -> Quantity['specific energy']:
        """Calculate the relative value for the gravitational potential energy (`potential_reference`), i.e. at `infinity`."""
        return self.poisson_potential(self.r_max * 100)

    def calculate_potential(self, r: Quantity['length']) -> Quantity['specific energy']:
        """Calculate the relative gravitational potential energy (`potential`) at a given radius `r`."""
        return cast(Quantity, self.potential_reference - self.poisson_potential(r))

    @cached_property
    def potential_grid(self) -> Quantity['specific energy']:
        """Calculate the relative gravitational potential (`potential`) at the  `internal logarithmic grid`."""
        return self.calculate_potential(self.geomspace_grid)

    @cached_property
    def integral_f(self) -> QuantitySpline:
        """Calculate the spline function for the antiderivative (`F`) of the distribution function (`f`)"""
        return physics.eddington.make_integral_f_spline(
            potential_grid=self.potential_grid,
            density_potential_spline=physics.eddington.make_density_potential_spline(
                potential_grid=self.potential_grid,
                density_grid=self.density_grid,
                s=self.spline_s,
            ),
        )

    def f(
        self,
        E: Quantity | None = None,
        r: Quantity | None = None,
        v: Quantity | None = None,
        reject_negative: bool = True,
    ) -> Quantity:
        """Calculate the distribution function (`f`) for the given energy."""
        if self.backend == 'agama':
            assert r is not None and v is not None, 'Radius and velocity must be provided for Agama backend'
            assert self.agama_df is not None, 'Agama distribution function not initialized'
            return self.agama_df(r=r, v=v).decompose(run_units.system)
        if E is None:
            assert r is not None and v is not None, 'Either energy or radius and velocity must be provided'
            E = self.E(r=r, v=v)
        return physics.eddington.f(E=E, integral_f_spline=self.integral_f, reject_negative=reject_negative)

    @cached_property
    def potential(self) -> QuantitySpline | Callable[[Quantity], Quantity]:
        """Interpolate the relative gravitational potential (`potential`) based on the  `internal logarithmic grid`."""
        if self.backend == 'agama':
            return self.calculate_potential
        return QuantitySpline(
            x=self.geomspace_grid.value,
            y=self.potential_grid.value,
            in_unit=str(self.geomspace_grid.unit),
            out_unit=str(self.potential_grid.unit),
            s=0,
        )

    def E(
        self,
        v: Quantity['velocity'],
        r: Quantity['length'] | None = None,
        potential: Quantity['specific energy'] | None = None,
    ) -> Quantity['specific energy']:
        """Interpolate the internal energy (`E`) At the given radius `r` using `potential()`."""
        if r is not None:
            return cast(Quantity, self.potential(r) - 1 / 2 * v**2)
        elif potential is not None:
            return cast(Quantity, potential - 1 / 2 * v**2)
        raise ValueError('Either `r` or `potential` must be provided')

    def invalidate(self, *properties: str):
        """Invalidates the cache for the specified properties, so they are recalculated."""
        for property in properties:
            if property == 'density':
                continue
            try:
                delattr(self, property)
            except AttributeError:
                pass

    @staticmethod
    def merge_distributions(distributions: list['Distribution'], inplace: bool = False) -> None:
        """Merges the `potential` grid values of the given distributions. Used to combine the potentials of multiple distributions to sample via Eddington's inversion."""
        physical_distributions = [density for density in distributions if density.physical]
        if any([distribution.backend == 'agama' for distribution in physical_distributions]):
            assert all([distribution.backend == 'agama' for distribution in physical_distributions]), (
                'All distributions must be in the same backend'
            )
            total_potential = agama_wrappers.Potential(
                *[distribution.agama_potential for distribution in distributions]
            )
            for distribution in physical_distributions:
                distribution.agama_total_potential = total_potential
        else:
            for distribution in physical_distributions:
                distribution.invalidate('potential_grid', 'potential_reference')
            potential_grid = sum([getattr(density, 'potential_grid') for density in physical_distributions])
            for distribution in physical_distributions:
                distribution.potential_grid = potential_grid

    ## io

    def save(self, path: str | Path, stem: str, verbose: bool = False) -> None:
        """Save the distribution to a file, handling the agama objects if present."""
        if verbose:
            print(f'Saving {stem}')
        io.save_distribution(path=path, stem=stem, distribution=self, **self.agama_save_params)

    @classmethod
    def load(cls, path: str | Path, stem: str) -> 'Distribution':
        """Load the distribution from a file, handling the agama objects if present."""
        return io.load_distribution(path=path, stem=stem)

    ## Roll initial setup

    def sample_r(
        self,
        n_particles: int | float,
        sampling_method: Literal['random', 'uniform'] = 'random',
        generator: np.random.Generator | None = None,
    ) -> Quantity['length']:
        """Sample particle positions from the distribution quantile function.

        Parameters:
            n_particles: Number of particles to sample.
            sampling_method: Sampling method to space the quantiles before applying the inverse CDF. If 'random' sample from a uniform random distribution. If 'uniform' use a uniform grid in the range (0,1). If 'uniform with boundaries' use a uniform grid in the range [0,1].
            generator: If not provided, use the default generator defined in `rng.generator`.

        Returns:
            Sampled particle positions.
        """
        if sampling_method == 'random':
            if generator is None:
                generator = rng.generator
            points = generator.random(int(n_particles))
        elif sampling_method == 'uniform':
            points = cast(NDArray[np.float64], np.linspace(0, 1, int(n_particles)))
        return cast(Quantity, np.sort(self.quantile_function(points)))

    @staticmethod
    @njit(parallel=True)
    def sample_v_norm_fast(
        potential: NDArray[np.float64],
        E_grid: NDArray[np.float64],
        f_grid: NDArray[np.float64],
        rolls: NDArray[np.float64],
        num: int = 100000,
    ) -> NDArray[np.float64]:
        """Sample particle velocity from the distribution function. Internal njit accelerated function. Prioritize using `roll_v()`."""
        output = np.empty_like(potential)
        for particle in prange(len(potential)):
            vs_grid = np.linspace(0, np.sqrt(2 * potential[particle]), num=num)
            vs = np.empty_like(vs_grid, dtype=np.float64)
            vs[:] = vs_grid
            pdf = np.zeros_like(vs)
            for i, v in enumerate(vs):
                pdf[i] = v**2 * utils.linear_interpolation(E_grid, f_grid, potential[particle] - v**2 / 2)
            pdf /= pdf.sum()
            cdf = np.cumsum(pdf)
            i = np.searchsorted(cdf, rolls[particle]) - 1
            if i < 0:
                i = 0
            elif i >= len(cdf) - 1:
                i = len(cdf) - 2
            output[particle] = vs[i]
        return output

    def sample_v_norm(
        self,
        r: Quantity['length'],
        num: int = 1000,
        generator: np.random.Generator | None = None,
    ) -> Quantity['velocity']:
        """Sample particle velocity (norm) from the distribution function.

        For full 3d velocity vectors, use `roll_v_3d()`.

        Parameters:
            r: Radius of the particles (required to sample the velocity, should have been sampled using `roll_v()` prior).
            num: Resolution parameters, defines the number of steps to use in the df integral.

        Returns:
            Sampled velocity norm of the particle, shaped `(num_particles,)`.
        """
        if generator is None:
            generator = rng.generator
        return Quantity(
            self.sample_v_norm_fast(
                potential=self.potential(r).to(run_units.specific_energy),
                E_grid=(E := cast(Quantity, np.sort(self.potential_grid))),
                f_grid=self.f(E=E),
                rolls=generator.random(len(r)),
                num=num,
            ),
            run_units.velocity,
        )

    def sample_v(
        self,
        r: Quantity['length'],
        num: int = 1000,
        generator: np.random.Generator | None = None,
    ) -> Quantity['velocity']:
        """Sample particle velocity (3d vectors) from the distribution function. Shape `(num_particles, 3)` with `(vx,vy,vr)`.

        The velocity is split into radial and perpendicular components by a uniform cosine distributed angle, and then the perpendicular component is split into x and y components by a uniform angle.
        See `roll_v()` for parameter details.
        """
        return cast(
            Quantity, np.vstack(utils.split_3d(self.sample_v_norm(r, generator=generator), generator=generator)).T
        )

    def sample_legacy(
        self,
        n_particles: int | float,
        sampling_method: Literal['random', 'uniform'] = 'random',
        num: int = 1000,
        generator: np.random.Generator | None = None,
    ) -> tuple[Quantity['length'], Quantity['velocity']]:
        """Sample particles In two steps:
            - Sample radius from the inversed CDF.
            - Calculate the velocity CDF for every particle's sampled radius, and sample from it's inverse.

        Parameters:
            n_particles: Number of particles to sample.
            sampling_method: Sampling method to space the quantiles before applying the inverse CDF. If 'random' sample from a uniform random distribution. If 'uniform' use a uniform grid in the range (0,1). If 'uniform with boundaries' use a uniform grid in the range [0,1].
            num: Resolution parameters, defines the number of steps to use in the df integral.
            generator: If not provided, use the default generator defined in `rng.generator`.

        Returns:
            A tuple of two vectors:
                Sampled radius values for each particle, shaped `(num_particles,)`
                Corresponding 3d velocities for each particle, shaped `(num_particles,3)`.
        """
        r = self.sample_r(n_particles, sampling_method=sampling_method, generator=generator).to(run_units.length)
        v = self.sample_v(r, num=num, generator=generator).to(run_units.velocity)
        return r, v

    def sample(
        self,
        n_particles: int | float,
        radius_min_value: Quantity['length'] | None = None,
        radius_max_value: Quantity['length'] | None = None,
        velocity_min_value: Quantity['velocity'] = Quantity(0, 'km/second'),
        velocity_max_value: Quantity['velocity'] | None = None,
        radius_resolution: int | float = 10000,
        velocity_resolution: int | float = 10000,
        radius_range: Quantity['length'] | None = None,
        velocity_range: Quantity['velocity'] | None = None,
        radius_noise: float = 1,
        velocity_noise: float = 1,
        fail_on_negative: bool = False,
        generator: np.random.Generator | None = None,
    ) -> tuple[Quantity['length'], Quantity['velocity']]:
        """Sample particles from the joint phase space distribution:
            - The distribution function `f` is transformed into a joint pdf proportional to `r^2*v^2*f(r,v)*drdv`.
            - The joint pdf is discretized on a grid of radius and velocity bins. If not provided directly (`radius_range`, `velocity_range`), a linear grid is constructed based on the rest of the parameters. The final row and column is dropped to facilitate the calculation of the `drdv` term.
            - The discretized distribution is flattened and sampled from using `generator.choice` with probability weights set by the bin value.
            - The sampled radius and velocity are perturbed by a uniform noise term to provide sub-pixel results.
            - Angles for the velocity split are sampled by `utils.split_3d()`.

        ** IF THE BACKEND IS 'AGAMA', THE ALL OPTIONS ARE IGNORED, AND THE SAMPLING IS HANDLED BY AGAMA **

        Parameters:
            n_particles: Number of particles to sample.
            radius_min_value: Minimum radius value to consider for the phase space distribution. If `None` use the quantile value for `0`. Regardless, this value is capped by `r_min` even if provided.
            radius_max_value: Maximum radius value to consider for the phase space distribution. If `None` use the quantile value for `1`. Regardless, this value is capped by `r_max` even if provided.
            velocity_min_value: Minimum velocity norm value to consider for the phase space distribution.
            velocity_max_value: Maximum velocity norm value to consider for the phase space distribution. If `None` use 1.5x the square maximum energy grid value.
            radius_resolution: Resolution of the radius grid.
            velocity_resolution: Resolution of the velocity grid.
            radius_range: Radius bins to use. If provided override the `radius_min_value`, `radius_max_value`, and `radius_resolution` parameters. If `None` ignores.
            velocity_range: Velocity bins to use. If provided override the `velocity_min_value`, `velocity_max_value`, and `velocity_resolution` parameters. If `None` ignores.
            radius_noise: Noise factor for the sampled radius values. The samples are perturbed by a uniform distribution in a symmetric interval with half-width `radius_noise * pixel width / 2`.
            velocity_noise: Noise factor for the sampled velocity values. Same logic as `radius_noise`.
            fail_on_negative: Whether to raise an error if the df grid is negative at any values, otherwise fill holes and continue.
            generator: If not provided, use the default generator defined in `rng.generator`.

        Returns:
            A tuple of two vectors:
                Sampled radius values for each particle, shaped `(num_particles,)`
                Corresponding 3d velocities for each particle, shaped `(num_particles,3)`.
        """
        if self.backend == 'agama':
            assert self.agama_df is not None, 'Agama distribution function not initialized'
            r, v, _ = self.agama_df.sample(n=n_particles)
            r, v = r[(i := np.argsort(r))], v[i]
            return r.decompose(run_units.system), v.decompose(run_units.system)
        if generator is None:
            generator = rng.generator
        if radius_range is None:
            if radius_min_value is None:
                radius_min_value = self.quantile_function(0)
            radius_min_value = max(radius_min_value, self.r_min)
            if radius_max_value is None:
                radius_max_value = self.quantile_function(1)
            radius_max_value = min(radius_max_value, self.r_max)
            radius_range = Quantity(np.linspace(radius_min_value, radius_max_value, int(radius_resolution)))
        if velocity_range is None:
            if velocity_max_value is None:
                # velocity_max_value = 1.5 * Quantity(np.sqrt(self.E_grid.max()))
                velocity_max_value = 1.5 * Quantity(np.sqrt(self.potential_grid.max())).to(velocity_min_value.unit)
            velocity_range = Quantity(np.linspace(velocity_min_value, velocity_max_value, int(velocity_resolution)))

        r_grid, v_grid = cast(
            tuple[Quantity, Quantity], np.meshgrid(radius_range[:-1], velocity_range[:-1], indexing='ij')
        )

        drdv = np.prod(np.meshgrid(radius_range.diff(), velocity_range.diff(), indexing='ij'), axis=0)
        probability_grid = np.array(16 * np.pi * r_grid**2 * v_grid**2 * self.f(self.E(v=v_grid, r=r_grid)) * drdv)
        probability_grid /= probability_grid.sum()
        flat_probability_grid = probability_grid.ravel()
        if (probability_grid < 0).any():
            if fail_on_negative:
                raise ValueError(f'Negative probability density encountered, {self}')
            else:
                probability_grid = cast(NDArray[np.float64], utils.smooth_holes_2d(probability_grid))
                probability_grid[probability_grid < 0] = 0

        indices = np.unravel_index(
            generator.choice(a=flat_probability_grid.size, size=int(n_particles), p=flat_probability_grid),
            probability_grid.shape,
        )

        r_indices, v_indices = indices + generator.uniform(
            [[min(1 - radius_noise, 0)], [min(1 - velocity_noise, 0)]],
            [[radius_noise], [velocity_noise]],
            (2, int(n_particles)),
        )

        r_indices, v_indices = np.abs(r_indices), np.abs(v_indices)
        r_indices[r_indices > radius_resolution - 2] = (
            2 * (radius_resolution - 2) - r_indices[r_indices > radius_resolution - 2]
        )
        v_indices[v_indices > velocity_resolution - 2] = (
            2 * (velocity_resolution - 2) - v_indices[v_indices > velocity_resolution - 2]
        )

        r_indices, v_indices = r_indices[np.argsort(r_indices)], v_indices[np.argsort(r_indices)]

        r_interp = scipy.interpolate.interp1d(np.arange(radius_resolution - 1), radius_range[:-1])
        v_interp = scipy.interpolate.interp1d(np.arange(velocity_resolution - 1), velocity_range[:-1])

        velocity = Quantity(v_interp(v_indices), velocity_range.unit)

        return (
            Quantity(r_interp(r_indices), radius_range.unit),
            cast(Quantity, np.vstack(utils.split_3d(velocity, generator=generator)).T),
        )

    def phase_space(self, **kwargs: Any) -> 'PhaseSpace':
        """Returns the phase space object matching the distribution."""
        from ..phase_space import PhaseSpace

        return PhaseSpace(self, **kwargs)

    def full_sample(
        self,
        n_particles: int | float,
        sample_method: Literal['distribution', 'phase space', 'legacy'] | None = None,
        phase_space_kwargs: dict[str, Any] = {},
        **kwargs: Any,
    ) -> tuple[
        Quantity['length'],
        Quantity['velocity'],
        Quantity['mass'],
        NDArray[np.str_],
        NDArray[np.int64],
    ]:
        """Samples particles from the distribution. Wraps the sample method and returns additional particle properties.

        If the backend is 'agama', the prefered (and default) sampling method is 'distribution' which is the agama backend's native sampling method. Otherwise, the prefered (and default) is 'phase space'.

        Parameters:
            n_particles: Number of particles to sample.
            sample_method: The method to use for sampling particles.
              - 'distribution': Samples particles from the distribution's distribution function (`df`) grid. Only works with linear grids.
              - 'phase space': Samples particles from the phase space object. Works with any grid.
              - 'legacy': Samples the particles' radius by sampling from the quantile m(r) distribution, and then for each particle calculate the velocity pdf from the distribution function (`df`), and sample from it's CDF. THERE IS SOME BUG IN THIS METHOD.

            **phase_space_kwargs: Additional keyword arguments to pass to the phase space object during initialization. Only relevant if `sample_method='phase space'`.
            **kwargs: Additional keyword arguments to pass to the sample method.

        Returns:
            The particles' position, velocity, mass, particle type, and distribution ID.
        """
        if sample_method is None:
            sample_method = 'distribution' if self.backend == 'agama' else 'phase space'

        if sample_method == 'distribution':
            r, v = self.sample(n_particles=n_particles, **kwargs)
        elif sample_method == 'phase space':
            r, v = self.phase_space(**phase_space_kwargs).sample_weighted_particles(n_particles=n_particles, **kwargs)
        elif sample_method == 'legacy':
            r, v = self.sample_legacy(n_particles=n_particles, **kwargs)
        return (
            r,
            v,
            cast(Quantity, np.ones(len(r)) * self.total_mass / len(r)),
            np.full(len(r), self.particle_type),
            np.full(len(r), self.id),
        )

    ##Plots

    def plot_phase_space(
        self,
        r_range: Quantity['length'] = Quantity(np.linspace(1e-2, 35, 200), 'kpc'),
        v_range: Quantity['velocity'] = Quantity(np.linspace(0, 60, 200), 'km/second'),
        velocity_unit: UnitLike = 'km/second',
        cmap: str = 'jet',
        transparent_value: float | None = 0,
        fix_negative_values: bool = True,
        plot_energy: bool = False,
        **kwargs: Any,
    ) -> tuple[Figure, Axes]:
        """Plot the phase space distribution of the density profile.

        Parameters:
            r_range: Range of radial distances to plot.
            v_range: Range of velocities to plot.
            velocity_unit: Units to use for the velocity axis.
            cmap: The colormap to use for the plot.
            transparent_value: Grid value to turn transparent (i.e. plot as `NaN`). If `None` ignores.
            fix_negative_values: Whether to fix negative values by interpolating them.
            plot_energy: Whether to plot the energy distribution instead of the density distribution.
            kwargs: Additional keyword arguments to pass to `plot.plot_phase_space()`.

        Returns:
            fig, ax.
        """
        r, v = cast(tuple[Quantity, Quantity], np.meshgrid(r_range, v_range))
        if plot_energy:
            grid = self.E(v=v, r=r)
        else:
            grid = 16 * np.pi * r**2 * v**2 * self.f(v=v, r=r)

        if fix_negative_values and not plot_energy and (grid < 0).any():
            y, x = np.indices(grid.shape)
            mask = grid < 0

            grid[mask] = Quantity(
                scipy.interpolate.griddata(
                    points=(x[~mask], y[~mask]), values=grid[~mask], xi=(x[mask], y[mask]), method='linear'
                ),
                grid.unit,
            )

        return plot.phase_space(
            grid,
            r_range,
            v_range,
            velocity_unit=velocity_unit,
            cmap=cmap,
            transparent_value=transparent_value,
            **kwargs,
        )

    def add_plot_radius_markers(self, ax: Axes, ymax: float, x_unit: UnitLike = 'kpc') -> Axes:
        """Add markers for the scale radius and virial radius to the plot."""
        ax.vlines(
            x=[self.r_s.to(x_unit).value, self.r_vir.to(x_unit).value],
            ymin=0,
            ymax=ymax,
            linestyles='dashed',
            colors='black',
        )
        ax.text(x=self.r_s.to(x_unit).value, y=ymax, s='r_s')
        ax.text(x=self.r_vir.to(x_unit).value, y=ymax, s='r_vir')
        return ax

    def plot_density(
        self,
        r_start: Quantity['length'] | None = None,
        r_end: Quantity['length'] | None = Quantity(1e4, 'kpc'),
        density_unit: UnitLike = 'Msun/kpc^3',
        length_unit: UnitLike = 'kpc',
        title: str | None = 'Density distribution (rho)',
        xlabel: str | None = 'Radius',
        ylabel: str | None = 'Density',
        label: str | None = None,
        add_markers: bool = True,
        xscale: 'plot.Scale' = 'log',
        yscale: 'plot.Scale' = 'log',
        lineplot_kwargs: dict[str, Any] = {},
        **kwargs: Any,
    ) -> tuple[Figure, Axes]:
        """Plot the density distribution (`rho`) of the density profile.

        Parameters:
            r_start: The starting radius for the plot. If `None`, uses `r_min`.
            r_end: The ending radius for the plot. If `None` uses `r_max`.
            density_unit: The unit for the density axis.
            length_unit: The unit for the radius axis.
            xscale: The scale of the x-axis.
            yscale: The scale of the y-axis.
            lineplot_kwargs: Additional keyword arguments to pass to `sns.lineplot()`.
            kwargs: Additional keyword arguments to pass to `plot.setup()`.

        Returns:
            fig, ax.
        """
        fig, ax = plot.setup(
            title=title,
            xlabel=xlabel,
            ylabel=ylabel,
            x_unit=length_unit,
            y_unit=density_unit,
            xscale=xscale,
            yscale=yscale,
            **kwargs,
        )

        if r_start is None:
            r_start = self.r_min
        if r_end is None:
            r_end = self.r_max

        r = cast(Quantity, np.geomspace(r_start, r_end, self.space_steps))
        density = self.density(r)
        sns.lineplot(x=r.to(length_unit).value, y=density.to(density_unit).value, ax=ax, label=label, **lineplot_kwargs)

        if add_markers:
            ax = self.add_plot_radius_markers(ax, ymax=density.max().to(density_unit).value, x_unit=length_unit)

        if label is not None:
            ax.legend()
        return fig, ax

    def plot_radius_distribution(
        self,
        r_start: Quantity['length'] | None = None,
        r_end: Quantity['length'] | None = None,
        cumulative: bool = False,
        length_unit: UnitLike = 'kpc',
        label: str | None = None,
        add_markers: bool = True,
        color: str = 'red',
        fig: Figure | None = None,
        ax: Axes | None = None,
        **kwargs: Any,
    ) -> tuple[Figure, Axes]:
        """Plot the radius distribution (`pdf`/`cdf`) of the density profile.

        Parameters:
            r_start: The starting radius for the plot. If `None` uses `r_min`.
            r_end: The ending radius for the plot. If `None` uses `r_max`.
            cumulative: Plot the `cdf`, if `False` plot the `pdf` instead.
            length_unit: The unit for the radius axis.
            label: The label for the plot (legend).
            add_markers: Whether to add markers to the plot.
            color: The color for the plot.
            fig: The figure to plot on.
            ax: The axes to plot on.
            kwargs: Additional keyword arguments for the plotting function (`sns.lineplot()`).

        Returns:
            fig, ax.
        """
        title = 'Particle cumulative range distribution (cdf)' if cumulative else 'Particle range distribution (pdf)'
        fig, ax = plot.setup(
            fig,
            ax,
            title=title,
            xlabel='Radius',
            ylabel='Density',
            x_unit=length_unit,
        )

        if r_start is None:
            r_start = self.r_min
        if r_end is None:
            r_end = self.r_max

        r = cast(Quantity, np.geomspace(r_start, r_end, self.space_steps))
        y = self.mass_cdf(r) if cumulative else self.mass_pdf(r)
        sns.lineplot(x=r.to(length_unit).value, y=y, color=color, ax=ax, label=label, **kwargs)
        if add_markers:
            ax = self.add_plot_radius_markers(ax, ymax=y.max(), x_unit=length_unit)
        return fig, ax

    def plot_drho_dpotential(
        self,
        xlabel: str | None = r'$\potential$',
        ylabel: str | None = r'$\frac{\mathrm{d}\rho}{\mathrm{d}\potential}$',
        title: str | None = 'Density derivative (log-log)',
        energy_unit: UnitLike = 'km^2/second^2',
        y_unit: UnitLike = 'Msun*second^2/(kpc^3*km^2)',
        fig: Figure | None = None,
        ax: Axes | None = None,
    ) -> tuple[Figure, Axes]:
        """Plot the density derivative with respect to the relative potential energy `drho/dpotential`.

        Parameters:
            xlabel: Label for the x-axis.
            ylabel: Label for the y-axis.
            energy_unit: Units for the energy axis.
            y_unit: Units for the y-axis.
            fig: Figure to plot on.
            ax: Axes to plot on.

        Returns:
            fig, ax
        """

        fig, ax = plot.setup(
            fig,
            ax,
            minorticks=True,
            xscale='log',
            yscale='log',
            xlabel=xlabel,
            ylabel=ylabel,
            x_unit=energy_unit,
            y_unit=y_unit,
            title=title,
        )
        sns.lineplot(
            x=np.array(self.potential_grid.to(energy_unit)), y=np.array(self.drho_dpotential_grid.to(y_unit)), ax=ax
        )
        return fig, ax

    def plot_f(
        self,
        E: Quantity['specific energy'] = Quantity(np.geomspace(50, 1800, 1000), 'km^2/second^2'),
        xlabel: str | None = r'$\mathcal{E}$',
        ylabel: str | None = 'f',
        title: str | None = 'Particle distribution function',
        energy_unit: UnitLike = 'km^2/second^2',
        f_unit: UnitLike = 'second^3/(kpc^3*km^3)',
        fig: Figure | None = None,
        ax: Axes | None = None,
    ) -> tuple[Figure, Axes]:
        """Plot the distribution function `f(E)`.

        Parameters:
            E: Energy values to plot.
            xlabel: Label for the x-axis.
            ylabel: Label for the y-axis.
            energy_unit: Units for the energy axis.
            f_unit: Units for the density function axis.
            fig: Figure to plot on.
            ax: Axes to plot on.

        Returns:
            fig, ax
        """

        fig, ax = plot.setup(
            fig,
            ax,
            minorticks=True,
            xscale='log',
            yscale='log',
            xlabel=xlabel,
            ylabel=ylabel,
            x_unit=energy_unit,
            y_unit=f_unit,
            title=title,
        )
        sns.lineplot(x=np.array(E.to(energy_unit)), y=np.array(self.f(E).to(f_unit)), ax=ax)
        return fig, ax
